flashcards/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^flashlearn/$', views.flashlearn, name='flashlearn'),
    url(r'^card/(?P<card_id>[0-9]+)/edit/$', views.edit_card, name='edit_card'),
    url(r'^card/add/$', views.add_card, name='add_card'),
    url(r'^card/(?P<card_id>[0-9]+)/delete/$', views.delete_card, name='delete_card'),
    url(r'^document/(?P<document_id>[0-9]+)/$', views.view_document, name='view_document'),
    url(r'^document/(?P<document_id>[0-9]+)/edit/$', views.edit_document, name='edit_document'),
    url(r'^scan/upload/$', views.upload_scan, name="upload_scan"),
    url(r'^library/$', views.view_library, name="view_library"),
    url(r'^login/$', views.login, name="login"),
]

flashlearn/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = [
    #url(r'^flashcards/', include('flashcards.urls', namespace="flashcards")),
    url(r'^', include('flashcards.urls', namespace="flashcards")),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace="auth")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += patterns('',
    (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
)

flashcards/models.py
from django.db import models
from django.conf import settings

class Card(models.Model):
    front_data = models.TextField()
    back_data = models.TextField()
    def __str__(self):
        return self.front_data

class Document(models.Model):
    document_name = models.CharField(max_length = 100)
    document_data = models.TextField()
    def __str__(self):
        return self.document_name

class Scan(models.Model):
    scan_data = models.ImageField(upload_to="scans/")

class UserDocument(models.Model):
    user_id = models.CharField(max_length = 10)
    document = models.ForeignKey(Document)
    def __str__(self):
        return "user_id: " + self.user_id + " document: " + str(self.document)

class DocumentCard(models.Model):
    document = models.ForeignKey(Document)
    card = models.ForeignKey(Card)
    def __str__(self):
        return "document: " + str(self.document) + " card: " + str(self.card)

flashcards/forms.py
from django import forms
from .models import *

class ScanUploadForm(forms.ModelForm):
    class Meta:
        model = Scan
        fields = '__all__'

class DocumentEditForm(forms.ModelForm):
    class Meta:
        model = Document
        fields = '__all__'

class CardEditForm(forms.ModelForm):
    class Meta:
        model = Card
        fields = '__all__'

flashcards/views.py
from django.http import Http404
from django.shortcuts import render
from django.shortcuts import redirect

from .models import *
from .forms import *

from django.http import HttpResponse
from django.conf import settings

from urllib.request import urlopen

def loggedin(request):
    return request.user and (not request.user.is_anonymous or request.user.pk is not None)

def index(request):
    if loggedin(request):
        return redirect("flashcards:flashlearn")
    else:
        return render(request, "flashcards/index.html")

def flashlearn(request):
    form = ScanUploadForm()
    return render(request, "flashcards/flashlearn.html", {'form': form, 'request': request, 'user': request.user})

def login(request):
    return render(request, "flashcards/login.html")

def view_document(request, document_id):
    form = DocumentEditForm()
    try:
        document = Document.objects.get(pk=document_id)
    except Document.DoesNotExist:
        raise Http404("Document doesn't exist")
    document_cards = DocumentCard.objects.all().filter(document=document)
    return render(request, "flashcards/document.html", {'document': document, 'card_deck': document_cards, 'form': form})

def add_card(request):
    if request.method == 'POST':
        form = CardEditForm(request.POST)
        if form.is_valid():
            c_document = request.POST['card_document']
            c_front = request.POST['front_data']
            c_back = request.POST['back_data']
            card = Card(front_data=c_front, back_data=c_back)
            card.save()
            card_document = DocumentCard(card=card, document=Document.objects.get(pk=c_document))
            card_document.save()
            return redirect("flashcards:view_document", document_id=card_document.document.pk)

def edit_card(request, card_id):
    if request.method == 'POST':
        form = CardEditForm(request.POST)
        if form.is_valid():
            try:
                card = Card.objects.get(pk=card_id)
            except Card.DoesNotExist:
                raise Http404("Card doesn't exist")
            c_front = request.POST['front_data']
            c_back = request.POST['back_data']
            card.front_data = c_front
            card.back_data = c_back
            card.save()
            card_document = DocumentCard.objects.get(card=card)
            return redirect("flashcards:view_document", document_id=card_document.document.pk)

def delete_card(request, card_id):
    card = Card.objects.get(pk=card_id)
    DocumentCard.objects.filter(card=card).delete()
    card.delete()
    if request.method == 'POST':
        card_document_id = request.POST['document_id']
        return redirect("flashcards:view_document", document_id=card_document_id)
    else:
        return redirect("flashcards:view_library")

def edit_document(request, document_id):
    if request.method == 'POST':
        try:
            document = Document.objects.get(pk=document_id)
        except Document.DoesNotExist:
            raise Http404("Document doesn't exist")
        d_name = request.POST['document_name']
        d_data = request.POST['document_data']
        document.document_name = d_name
        document.document_data = d_data
        document.save()
        return redirect("flashcards:view_document", document_id=document_id)

def view_library(request):
    if loggedin(request):
        user_docs = UserDocument.objects.all().filter(user_id=request.user.pk)
        return render(request, "flashcards/library.html", {'userlibrary': user_docs})
    else:
        return redirect("flashcards:index")

def upload_scan(request):
    if request.method == 'POST':
        new_scan = Scan(scan_data = request.FILES['scan_data'])
        new_scan.save()
        link = "http://104.131.48.234/witchcraft/dostuff.php"
        f = urlopen(link)
        file1 = f.read()
        front = str(file1)
        link2 = "http://104.131.48.234/witchcraft/dostuff2.php"
        f2 = urlopen(link2)
        file2 = f2.read();
        back = str(file2)
        documenttext = front + back
        d = Document(document_name=front, document_data = documenttext)
        d.save()
        c = Card(front_data=front,back_data=back);
        c.save()
        dc = DocumentCard(document=d,card=c)
        dc.save()
        ud = UserDocument(user_id=request.user.pk,document=d)
        ud.save()
        return redirect("flashcards:view_library")

flashcards/templates/flashcards/document.html
<!DOCTYPE html>
<html>
<head>
    <title>FlashLearn</title>
    <link rel="stylesheet" type="text/css" href="/static/style.css"/>
    <link rel="stylesheet" type="text/css" href="/static/background.css"/>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,600' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="/static/slick-1.5.7/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="/static/slick-1.5.7/slick/slick-theme.css"/>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="/static/slick-1.5.7/slick/slick.min.js"></script>
    <script type="text/javascript">
    $(document).ready(function() {
      $('.indexcard').slick({accessibility: true});
        {% for c in card_deck %}
        $("#card{{ c.card.pk }}").click(function(){
          $("#front{{ c.card.pk }}").toggle();
          $("#back{{ c.card.pk }}").toggle();
        });
        {% endfor %}
        $("#documentedit").click(function() {
          $('#documentpane').toggle();
        });
        $("#cardedit").click(function() {
          $("#cardpane").toggle();
        });
    });
    </script>
</head>
  <body>
      <nav>
          <a href="{% url 'flashcards:index' %}"><img src="/static/FlashLearnLogo.png"/></a>
          <ul>
            {% if user and not user.is_anonymous %}
            <li>Hello {{ user.get_full_name|default:user.username}}!</li>
            <li><a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a></li>
            {% endif %}
            <li><a href="{% url 'flashcards:view_library' %}">documents</a></li>
            <li><a href="{% url 'flashcards:flashlearn' %}">upload</a></li>
          </ul>
      </nav>
      <div id = "wrapper">
      <div class="content" id="cardviewer">
          <div class="indexcard">
              <!--for each card-->
              {% for c in card_deck %}
              <div class="card" id="card{{ c.card.pk }}"><div id="front{{ c.card.pk }}"><p>{{ c.card.front_data }}</p></div><div hidden id="back{{ c.card.pk }}"><p>{{ c.card.back_data }}</p></div></div>
              {% endfor %}
          </div>
        </div>
        <div class="editbuttons" id="documentedit">
             Document
        </div>
        <div hidden id="documentpane">
          <div id="dpane">
            <form method="post" action="{% url 'flashcards:edit_document' document.pk %}">
              {% csrf_token %}
              <input name="document_name" type="text" value="{{ document.document_name }}" />
              <textarea name="document_data" rows = "5" cols = "120">
                {{ document.document_data }}
              </textarea>
              <input type="submit" value="Submit" />
            </form>
          </div>
          </div>
        <div class="editbuttons" id="cardedit">
            Cards
        </div>
        <div hidden id="cardpane">
          <div id="ncpane">
            <form method="post" action="{% url 'flashcards:add_card' %}">
              {% csrf_token %}
              <input type="hidden" name="card_document" value="{{ document.pk }}" />
              <input placeholder="Front" name="front_data" type="text" />
              <input placeholder="Back" name="back_data" type="text" />
              <input type="submit" value="Submit" />
            </form>
          </div>
          {% for c in card_deck %}
            <div id="cpane{{ c.card.pk }}">
              <form method="post" action="{% url 'flashcards:edit_card' c.card.pk %}">
                {% csrf_token %}
                <input name="front_data" type="text" value="{{ c.card.front_data }}"/>
                <input name="back_data" type="text" value="{{ c.card.back_data }}"/>
                <input type="submit" value="Submit" />
              </form>
              <form method="post" action="{% url 'flashcards:delete_card' c.card.pk %}">
                {% csrf_token %}
                <input type="hidden" name="document_id" value="{{ document.pk }}" />
                <input type="submit" value="Delete" />
              </form>
            </div>
          {% endfor %}
        </div>
      </div>
    </body>
</html>

flashcards/templates/flashcards/flashlearn.html
<!DOCTYPE html>
<html>
<head>
    <title>FlashLearn</title>
    <link rel="stylesheet" type="text/css" href="/static/style.css"/>
    <link rel="stylesheet" type="text/css" href="/static/background.css"/>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,600' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="/static/script.js"></script>
</head>
  <body>
      <nav>
        <a href="{% url 'flashcards:index' %}"><img src="/static/FlashLearnLogo.png"/></a>
          <ul>
              {% if user and not user.is_anonymous %}
              <li>Hello {{ user.get_full_name|default:user.username}}!</li>
              <li><a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a></li>
              {% else %}
              <li><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a></li>
              {% endif %}
              <li><a href="{% url 'flashcards:view_library' %}">documents</a></li>
              <li><a href="{% url 'flashcards:flashlearn' %}">upload</a></li>
          </ul>
      </nav>
        <div class="content">
            Upload your textbook image.
            <form action = "{% url 'flashcards:upload_scan' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div id="uploadcontainer">
                    <label class="filecontainer">
                        <input type="file" name="scan_data" accept="image/gif, image/jpeg, image/png">
                    </label>
                    <input type="submit"value="Submit" id="submitbutton">
                </input>
                </div>
            </form>
        </div>
    </body>
</html>

flashcards/templates/flashcards/index.html
<!DOCTYPE html>
<html>
    <head>
        <title>FlashLearn</title>
        <link rel="stylesheet" type="text/css" href="/static/style.css"/>
        <link rel="stylesheet" type="text/css" href="/static/stylehome.css"/>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,600' rel='stylesheet' type='text/css'>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
        <script src="/static/script.js"></script>
    </head>
    <body>
        <nav>
          <a href="{% url 'flashcards:index' %}"><img src="/static/FlashLearnLogo.png"/></a>
            <ul>
                {% if user and not user.is_anonymous %}
                <li>Hello {{ user.get_full_name|default:user.username}}!</li>
                <li id="first"><a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a></li>
                {% else %}
                <li id="first"><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a></li>
                {% endif %}
                <li><a href="{% url 'flashcards:flashlearn' %}">upload</a></li>
                <li><a href="{% url 'flashcards:view_library' %}">documents</a></li>
            </ul>
        </nav>
        <div class = "content">
            <div id="slide1" class="slide">
                <p id="text">Transform your textbooks into flashcards</p>
                <div class="clearfix">
                    <img id="circle1" src="static/CircleTextbook.png" height="25%" width="25%"/>
                    <img id="arrow" src="static/arrow.png" height="15%" width="15%"/>
                    <img id="circle2" src="static/CircleNote.png" height="25%" width="25%"/>
                </div>
            </div>
            <div id="slide2" class ="slide">
                <p>Upload the textbook file as a .png, .jpg, or .gif. </p>
                <clearfix>
                <div id="half">
                <!-- <img src="static/textbook.png" height="360" width="288"/> -->
                <img src="static/tripletexts.png" height="370px" width="350px"/>
                </div>
                <div id="otherhalf">
                <a href="{% url 'flashcards:flashlearn' %}"><button class="button"><font size="6">UPLOAD</font></button></a>
                </div>
            </clearfix>
            </div>
            <div id="slide3" class="slide">
                <p>Pytesseract and Opencv <i>extract</i> your <b>bolded</b> words<br> and
                   <i>save</i> the definitions as flashcards.</p>
            </div>
        </div>
        <div id="footer">
            <span> Jason Wu | Jonathan Zhang | Marisa Hoenig | Cayla Vinzons</span
            HackGT 2015
        </div>
    </body>
</html>

flashcards/templates/flashcards/library.html
<!DOCTYPE html>
{% csrf_token %}
<html>
<head>
    <title>FlashLearn</title>
    <link rel="stylesheet" type="text/css" href="/static/style.css"/>
    <link rel="stylesheet" type="text/css" href="/static/background.css"/>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300,600' rel='stylesheet' type='text/css'>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="/static/script.js"></script>
</head>
  <body>
    <nav>
      <a href="{% url 'flashcards:index' %}"><img src="/static/FlashLearnLogo.png"/></a>
        <ul>
            {% if user and not user.is_anonymous %}
            <li>Hello {{ user.get_full_name|default:user.username}}!</li>
            <li><a href="{% url 'auth:logout' %}?next={{ request.path }}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">Login with Google</a></li>
            {% endif %}
            <li><a href="{% url 'flashcards:view_library' %}">documents</a></li>
            <li><a href="{% url 'flashcards:flashlearn' %}">upload</a></li>
        </ul>
    </nav>
      <div class="content">
          <div id="libraryhead">Library</div>
          {% for userdoc in userlibrary %}
          <div id="doc">
              <a href="{% url 'flashcards:view_document' userdoc.document.pk %}">{{userdoc.document.document_name}}</a>
          </div>
          {% endfor %}
        <br>
<!-- <button>Make Flashcards</button>
        Button to convert to flashcards, which leads to <a href="cardviewer.html">View</a>. -->
      </div>
  </body>
</html>

flashcards/templates/flashcards/login.html
LOG IN